import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  InterviewSidebar: [
    {
      type: 'category',
      label: '面试题',
      link: {
        type: 'generated-index',
        description: 'Java 后端、数据库、Redis、微服务、JVM 等领域知识点。',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'interview-questions',
        },
      ],
    },
  ],
  FrameworkSidebar: [
    {
      type: 'autogenerated',
      dirName: 'interview-questions/框架篇',
    },
  ],
  RedisSidebar: [
    {
      type: 'autogenerated',
      dirName: 'interview-questions/redis篇',
    },
  ],
  MicroserviceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'interview-questions/微服务篇',
    },
  ],
  AiAgentSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai-agent',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
